// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIgbH7cWlg1oZM6m54fhoZ34DK00rv4C4',
    appId: '1:354020395968:web:067c565769bd5f54d25625',
    messagingSenderId: '354020395968',
    projectId: 'kanriapuri-2bf0c',
    authDomain: 'kanriapuri-2bf0c.firebaseapp.com',
    storageBucket: 'kanriapuri-2bf0c.appspot.com',
    measurementId: 'G-5KX2TVPP1S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9BxagkqZxZMNgI_SA_Po8GzedzgMc04M',
    appId: '1:354020395968:android:657bc556d9dd4f2bd25625',
    messagingSenderId: '354020395968',
    projectId: 'kanriapuri-2bf0c',
    storageBucket: 'kanriapuri-2bf0c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_DGcXAakFrMk6kmslI93Fqa2EJNK258Y',
    appId: '1:354020395968:ios:5dac359661a394c1d25625',
    messagingSenderId: '354020395968',
    projectId: 'kanriapuri-2bf0c',
    storageBucket: 'kanriapuri-2bf0c.appspot.com',
    iosBundleId: 'com.example.work1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_DGcXAakFrMk6kmslI93Fqa2EJNK258Y',
    appId: '1:354020395968:ios:b789c8405340c508d25625',
    messagingSenderId: '354020395968',
    projectId: 'kanriapuri-2bf0c',
    storageBucket: 'kanriapuri-2bf0c.appspot.com',
    iosBundleId: 'com.example.work1.RunnerTests',
  );
}
